# Generated by Django 3.0.6 on 2020-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Male'), ('2', 'Female')], null=True),
        ),
    ]
