# Generated by Django 3.0.6 on 2020-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('bombay', 'Bombay')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street_Line_1',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street_Line_2',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
