# Generated by Django 3.0.6 on 2020-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200524_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
