# Generated by Django 3.0.6 on 2020-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200524_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_Patient',
            field=models.BooleanField(default=False, verbose_name='Patient Status'),
        ),
    ]
