# Generated by Django 3.0.6 on 2020-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200524_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
    ]
