# Generated by Django 3.0.6 on 2020-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_doctor_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Active')], default='Inactive', max_length=15),
        ),
    ]
