# Generated by Django 3.0.6 on 2020-05-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='outstandiing',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='paid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=15),
        ),
    ]
