# Generated by Django 3.0.6 on 2020-05-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200525_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='outstandiing',
            new_name='outstanding',
        ),
    ]
